import type {NextPage} from 'next'
import Head from 'next/head'
import axios, {AxiosResponse} from "axios";

type ApiReturn = {
    data: any[],
    message: string
}

const Home: NextPage = () => {

    function testConnection(): void {
        axios.get('http://localhost:3000/notes/get').then((response: AxiosResponse<ApiReturn>) => {
            console.log(response.data.message);
        })
    }

    return (
        <div className={'flex justify-center pt-12'}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1 className="text-3xl text-green-500 font-bold">hello world!</h1>
                <button onClick={testConnection} className={'p-3 border border-blue-500 rounded'}>Test Connection</button>
            </main>
        </div>
    )
}

export default Home
